[phases.setup]
nixPkgs = ["openjdk17", "maven"]

[phases.build]
cmds = ["cd backend/prashant_portfolio && chmod +x mvnw && ./mvnw clean package -DskipTests"]

[start]
cmd = "cd backend/prashant_portfolio && java -jar target/portfolio-0.0.1-SNAPSHOT.jar"
